services:
  - type: web
    name: event-driver-noti
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache
          property: connectionString
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: ADMIN_SIGNUP_CODE
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: redis
    name: redis-cache
    ipAllowList: [] # Only allow internal connections
